DROP TABLE IF EXISTS CUSTOMER;
  
CREATE TABLE CUSTOMER (
    CUSTOMER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(255) NOT NULL
);



DROP TABLE IF EXISTS TRANSACTION;
  
CREATE TABLE TRANSACTION (
    TRANSACTION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID BIGINT NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    TRANSACTION_DATE TIMESTAMP NOT NULL
);

